export const fontFamilys = [
  {
    name: '默认',
    ttf: 'https://cdn.h5ds.com/assets/fonts/siYuanHeiTi/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/siYuanHeiTi/font.woff',
    thumb: '',
  },
  {
    name: 'aZhuPaoPao',
    ttf: 'https://cdn.h5ds.com/assets/fonts/aZhuPaoPao/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/aZhuPaoPao/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/aZhuPaoPao/img.png',
  },
  {
    name: 'baoTuXiaoBai',
    ttf: 'https://cdn.h5ds.com/assets/fonts/baoTuXiaoBai/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/baoTuXiaoBai/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/baoTuXiaoBai/img.png',
  },
  {
    name: 'cangErFeiBaiW01',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErFeiBaiW01/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErFeiBaiW01/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErFeiBaiW01/img.png',
  },
  {
    name: 'cangErFeiBaiW05',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErFeiBaiW05/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErFeiBaiW05/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErFeiBaiW05/img.png',
  },
  {
    name: 'cangErSuYuanTiW01',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErSuYuanTiW01/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErSuYuanTiW01/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErSuYuanTiW01/img.png',
  },
  {
    name: 'cangErSuYuanTiW05',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErSuYuanTiW05/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErSuYuanTiW05/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErSuYuanTiW05/img.png',
  },
  {
    name: 'cangErXiaoWanZi',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErXiaoWanZi/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErXiaoWanZi/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErXiaoWanZi/img.png',
  },
  {
    name: 'cangErYuMoW01',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErYuMoW01/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErYuMoW01/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErYuMoW01/img.png',
  },
  {
    name: 'cangErYuMoW05',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErYuMoW05/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErYuMoW05/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErYuMoW05/img.png',
  },
  {
    name: 'cangErYuYangW01',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErYuYangW01/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErYuYangW01/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErYuYangW01/img.png',
  },
  {
    name: 'cangErYuYangW05',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErYuYangW05/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErYuYangW05/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErYuYangW05/img.png',
  },
  {
    name: 'cangErZhouKeZhengDaBangShu',
    ttf: 'https://cdn.h5ds.com/assets/fonts/cangErZhouKeZhengDaBangShu/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/cangErZhouKeZhengDaBangShu/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/cangErZhouKeZhengDaBangShu/img.png',
  },
  {
    name: 'chuangQiNanAn',
    ttf: 'https://cdn.h5ds.com/assets/fonts/chuangQiNanAn/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/chuangQiNanAn/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/chuangQiNanAn/img.png',
  },
  {
    name: 'chuanQiTeZhan',
    ttf: 'https://cdn.h5ds.com/assets/fonts/chuanQiTeZhan/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/chuanQiTeZhan/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/chuanQiTeZhan/img.png',
  },
  {
    name: 'gongFan',
    ttf: 'https://cdn.h5ds.com/assets/fonts/gongFan/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/gongFan/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/gongFan/img.png',
  },
  {
    name: 'naiHu',
    ttf: 'https://cdn.h5ds.com/assets/fonts/naiHu/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/naiHu/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/naiHu/img.png',
  },
  {
    name: 'pangMenBiaoTi',
    ttf: 'https://cdn.h5ds.com/assets/fonts/pangMenBiaoTi/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/pangMenBiaoTi/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/pangMenBiaoTi/img.png',
  },
  {
    name: 'ruiZiZhenYan',
    ttf: 'https://cdn.h5ds.com/assets/fonts/ruiZiZhenYan/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/ruiZiZhenYan/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/ruiZiZhenYan/img.png',
  },
  {
    name: 'shiJieFaGun',
    ttf: 'https://cdn.h5ds.com/assets/fonts/shiJieFaGun/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/shiJieFaGun/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/shiJieFaGun/img.png',
  },
  {
    name: 'siYuanHeiTi',
    ttf: 'https://cdn.h5ds.com/assets/fonts/siYuanHeiTi/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/siYuanHeiTi/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/siYuanHeiTi/img.png',
  },
  {
    name: 'yanShiFoXi',
    ttf: 'https://cdn.h5ds.com/assets/fonts/yanShiFoXi/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/yanShiFoXi/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/yanShiFoXi/img.png',
  },
  {
    name: 'zaiZaiJia',
    ttf: 'https://cdn.h5ds.com/assets/fonts/zaiZaiJia/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/zaiZaiJia/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/zaiZaiJia/img.png',
  },
  {
    name: 'zhanKuKuaiLe',
    ttf: 'https://cdn.h5ds.com/assets/fonts/zhanKuKuaiLe/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/zhanKuKuaiLe/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/zhanKuKuaiLe/img.png',
  },
  {
    name: 'zhanKuKuHei',
    ttf: 'https://cdn.h5ds.com/assets/fonts/zhanKuKuHei/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/zhanKuKuHei/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/zhanKuKuHei/img.png',
  },
  {
    name: 'zhengQingKeHuangYou',
    ttf: 'https://cdn.h5ds.com/assets/fonts/zhengQingKeHuangYou/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/zhengQingKeHuangYou/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/zhengQingKeHuangYou/img.png',
  },
  {
    name: 'zhuangJiaMingChao',
    ttf: 'https://cdn.h5ds.com/assets/fonts/zhuangJiaMingChao/font.ttf',
    url: 'https://cdn.h5ds.com/assets/fonts/zhuangJiaMingChao/font.woff',
    thumb: 'https://cdn.h5ds.com/assets/fonts/zhuangJiaMingChao/img.png',
  },
];
