export const tdata: any = {
  name: 'mock数据',
  desc: '暂无描述',
  version: '1.0.0',
  thumb: '',
  createTime: 0,
  updateTime: 0,
  selectPageId: 'p1',
  pages: [
    {
      id: 'p1',
      name: 'p1',
      desc: '',
      width: 1000,
      height: 600,
      background: { type: 'solid', color: '#fff' },
      layers: [],
    },
    {
      id: 'dgAIEp_aIx',
      name: '空白页面',
      desc: '页面描述',
      width: 800,
      height: 1200,
      thumb:
        'https://cdn.h5ds.com/uploads/s/20201023/723924b42b0e0333db04d2de0408fd5562a16f61.png?x-oss-process=image/resize,m_lfit,w_320/quality,q_80',
      background: { type: 'solid', color: '#ffffff' },
      layers: [
        {
          type: 'text',
          fontFamilyURL: '',
          text: '2020',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 16,
            fill: 'rgba(222,222,222,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'HvQIhNR6aLxi9cVk',
          name: '文字元素',
          desc: '描述',
          x: 733.501,
          y: 21,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '呵护牙周',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 17,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'CTxjpRhlRO9-oKaP',
          name: '文字元素',
          desc: '描述',
          x: 650,
          y: 1025.62,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '抑菌去渍',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 17,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'FvgXYoCDL1q-SwGF',
          name: '文字元素',
          desc: '描述',
          x: 520,
          y: 1025.62,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '预防蛀牙',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 17,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'x-1IwrdFUzApFlMz',
          name: '文字元素',
          desc: '描述',
          x: 387,
          y: 1025.62,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '清新口气',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 17,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: '8QYs-Pfl9wuVbBWT',
          name: '文字元素',
          desc: '描述',
          x: 650,
          y: 922.986,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '去除牙垢',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 17,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'YfXBPwPuN6_5EUFS',
          name: '文字元素',
          desc: '描述',
          x: 520,
          y: 921.986,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '绽放笑容',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 24,
            fill: 'rgba(170,170,170,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'Y6hOlzYszGeTjMKu',
          name: '文字元素',
          desc: '描述',
          x: 680.99,
          y: 680.682,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '满嘴飘香',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 24,
            fill: 'rgba(170,170,170,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'ooTPmmXZWBnAYegC',
          name: '文字元素',
          desc: '描述',
          x: 563,
          y: 680.682,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '清洁\n如玉',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 24,
            fill: 'rgba(170,170,170,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'wZc3ljhUX7aDIilA',
          name: '文字元素',
          desc: '描述',
          x: 440.99,
          y: 680.682,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '59.8',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 90,
            fill: 'rgba(216,170,29,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'OvTN6s5Fm3JYpVRF',
          name: '文字元素',
          desc: '描述',
          x: 91.9886,
          y: 644.773,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '净化口腔雾霾，\n留下阳光微笑。',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 17,
            fill: 'rgba(170,170,170,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'oo8u4jtay-OEZR1K',
          name: '文字元素',
          desc: '描述',
          x: 60,
          y: 347,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL: '',
          text: '尊享\n品质',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 77,
            fill: 'rgba(216,170,29,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'S6cph7oTAM9B8Lus',
          name: '文字元素',
          desc: '描述',
          x: 60,
          y: 146,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'image',
          width: 188,
          height: 158,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_33.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'TcG_Zqaqg7Uwchrb',
          name: '图片元素',
          desc: '描述信息',
          x: 100,
          y: 909,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 158,
          naturalWidth: 188,
        },
        {
          type: 'image',
          width: 30,
          height: 30,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_31.png',
          cornerRadius: [0, 0, 0, 0],
          id: '7d8LsRVK3FWiNwg4',
          name: '图片元素',
          desc: '描述信息',
          x: 608,
          y: 1022,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 30,
          naturalWidth: 30,
        },
        {
          type: 'image',
          width: 30,
          height: 30,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_29.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'AKDh18MadZdH9mOs',
          name: '图片元素',
          desc: '描述信息',
          x: 477,
          y: 1022,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 30,
          naturalWidth: 30,
        },
        {
          type: 'image',
          width: 30,
          height: 30,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_27.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'zntDNgFdIy_0do7W',
          name: '图片元素',
          desc: '描述信息',
          x: 345,
          y: 1022,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 30,
          naturalWidth: 30,
        },
        {
          type: 'image',
          width: 30,
          height: 30,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_25.png',
          cornerRadius: [0, 0, 0, 0],
          id: '2Jj6f7jkzLHXzlk7',
          name: '图片元素',
          desc: '描述信息',
          x: 608,
          y: 918,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 30,
          naturalWidth: 30,
        },
        {
          type: 'image',
          width: 30,
          height: 30,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_23.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'zwvW9MWF-Guwk3Qq',
          name: '图片元素',
          desc: '描述信息',
          x: 477,
          y: 918,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 30,
          naturalWidth: 30,
        },
        {
          type: 'image',
          width: 30,
          height: 30,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_21.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'eeAH5IqbYgJ5PYHY',
          name: '图片元素',
          desc: '描述信息',
          x: 345,
          y: 919.993,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 30,
          naturalWidth: 30,
        },
        {
          type: 'image',
          width: 727,
          height: 352,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_20.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'AjWyPEBI0BtQTE1-',
          name: '图片元素',
          desc: '描述信息',
          x: 33,
          y: 810,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 352,
          naturalWidth: 727,
        },
        {
          type: 'image',
          width: 94,
          height: 28,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_19.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'SaYmhACFyLARgEhl',
          name: '图片元素',
          desc: '描述信息',
          x: 61,
          y: 596,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 28,
          naturalWidth: 94,
        },
        {
          type: 'image',
          width: 19,
          height: 396,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_18.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'ApaV0CrFWBOCIh-J',
          name: '图片元素',
          desc: '描述信息',
          x: 730,
          y: 95,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 396,
          naturalWidth: 19,
        },
        {
          type: 'image',
          width: 93,
          height: 93,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_15.png',
          cornerRadius: [0, 0, 0, 0],
          id: '9O1OTxSmbWGiT4kq',
          name: '图片元素',
          desc: '描述信息',
          x: 147,
          y: 35,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 93,
          naturalWidth: 93,
        },
        {
          type: 'image',
          width: 37,
          height: 6,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_14.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'KVfX_6LHWfETZQIU',
          name: '图片元素',
          desc: '描述信息',
          x: 73,
          y: 55,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 6,
          naturalWidth: 37,
        },
        {
          type: 'image',
          width: 157,
          height: 11,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_13.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'q2-XFdMTnvqDC_43',
          name: '图片元素',
          desc: '描述信息',
          x: 60,
          y: 411,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 11,
          naturalWidth: 157,
        },
        {
          type: 'image',
          width: 55,
          height: 49,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_11.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'ty4WKOa1RopVESpT',
          name: '图片元素',
          desc: '描述信息',
          x: 65,
          y: 75,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 49,
          naturalWidth: 55,
        },
        {
          type: 'image',
          width: 88,
          height: 27,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_10.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'EeHiVx7YoEvkEDaD',
          name: '图片元素',
          desc: '描述信息',
          x: 593,
          y: 52,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 27,
          naturalWidth: 88,
        },
        {
          type: 'image',
          width: 98,
          height: 85,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_6.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'tJEMqgWxfvtp-_OZ',
          name: '图片元素',
          desc: '描述信息',
          x: 657,
          y: 670,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 85,
          naturalWidth: 98,
        },
        {
          type: 'image',
          width: 99,
          height: 85,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_5.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'UJxoFz-dhbq2-zBE',
          name: '图片元素',
          desc: '描述信息',
          x: 538,
          y: 670,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 85,
          naturalWidth: 99,
        },
        {
          type: 'image',
          width: 98,
          height: 85,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_4.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'KX0r7vQVr2ldvUsk',
          name: '图片元素',
          desc: '描述信息',
          x: 417,
          y: 670,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 85,
          naturalWidth: 98,
        },
        {
          type: 'image',
          width: 14,
          height: 20,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_3.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'iTlpKYtkbcleuuN1',
          name: '图片元素',
          desc: '描述信息',
          x: 60,
          y: 713,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 20,
          naturalWidth: 14,
        },
        {
          type: 'image',
          width: 394,
          height: 452,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_2.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'rZLhZONmBp6FCN_C',
          name: '图片元素',
          desc: '描述信息',
          x: 251,
          y: 150,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 452,
          naturalWidth: 394,
        },
        {
          type: 'image',
          width: 1086,
          height: 1201,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9739/20201023/1603440371906_layer_1.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'U_VGJySW2JW6A7LA',
          name: '图片元素',
          desc: '描述信息',
          x: -132,
          y: -0.994263,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 1201,
          naturalWidth: 1086,
        },
      ],
    },
    {
      id: 'mSY_l2Xmtd',
      name: '空白页面',
      desc: '页面描述',
      width: 1242,
      height: 2208,
      thumb:
        'https://cdn.h5ds.com/uploads/s/20201110/3d5a3fea7cd410487b3adbc18a9c886f544f1896.png?x-oss-process=image/resize,m_lfit,w_320/quality,q_80',
      background: { type: 'solid', color: '#ffffff' },
      layers: [
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '扫码进入直播间',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 34,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'xGfV93RxLJEbS9H-',
          name: '文字元素',
          desc: '描述',
          x: 952,
          y: 2139,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '直播时间:11月11日20:00',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 55,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'hUtQn4PYzWInpOGc',
          name: '文字元素',
          desc: '描述',
          x: 290,
          y: 2053,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '更有各种优惠满减',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 55,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'yRRDn6jBmZ-Ms3FW',
          name: '文字元素',
          desc: '描述',
          x: 471,
          y: 1976,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '百量无门槛优惠券',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 55,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
            strokeWidth: 1,
          },
          id: 'P8Fw9CV9QVN6Bscp',
          name: '文字元素',
          desc: '描述',
          x: 471,
          y: 1898,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E5%AE%8B%E4%BD%93/%E6%80%9D%E6%BA%90%E5%AE%8B%E4%BD%93.otf',
          text: '看\n直\n播\n限\n时\n特\n惠',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源宋体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 80,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
            strokeWidth: 1,
          },
          id: 'jmFyggRLHQmy3x5f',
          name: '文字元素',
          desc: '描述',
          x: 1109,
          y: 431,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '起',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 48,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
          },
          id: 'scdOSAXZENRqHn3A',
          name: '文字元素',
          desc: '描述',
          x: 257,
          y: 1134,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
          text: '8折',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '思源黑体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 131,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
            strokeWidth: 1,
          },
          id: '-NkkqnsE6FVPneCF',
          name: '文字元素',
          desc: '描述',
          x: 52,
          y: 1040,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E8%A3%85%E7%94%B2%E6%98%8E%E6%9C%9D%E4%BD%93/SoukouMincho.ttf',
          text: '双11直播间>>',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '装甲明朝体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 97,
            fill: 'rgba(245,182,7,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
            strokeWidth: 1,
          },
          id: 'QhrMg3mc6LhJPGvT',
          name: '文字元素',
          desc: '描述',
          x: 45,
          y: 335,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'text',
          fontFamilyURL:
            'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E8%A3%85%E7%94%B2%E6%98%8E%E6%9C%9D%E4%BD%93/SoukouMincho.ttf',
          text: 'LOGO',
          fill: '',
          textStyle: {
            textDecoration: 'normal',
            textAlign: 'left',
            fontFamily: '装甲明朝体',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fontSize: 97,
            fill: 'rgba(255,255,255,1)',
            letterSpacing: { value: 0, type: 'percent' },
            lineHeight: { value: 150, type: 'percent' },
            strokeWidth: 1,
          },
          id: 'CFzlWjr6MP7EN95K',
          name: '文字元素',
          desc: '描述',
          x: 45,
          y: 196,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.5)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
        },
        {
          type: 'image',
          width: 224,
          height: 224,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_6.png',
          cornerRadius: [0, 0, 0, 0],
          id: '_hIyQNHl1yNDaQwL',
          name: '图片元素',
          desc: '描述信息',
          x: 958,
          y: 1896,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 224,
          naturalWidth: 224,
          _ratio: 1,
        },
        {
          type: 'image',
          width: 330,
          height: 330,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_4.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'tA_00g-ND3IK6dF7',
          name: '图片元素',
          desc: '描述信息',
          x: 18,
          y: 976,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 330,
          naturalWidth: 330,
        },
        {
          type: 'image',
          width: 1099,
          height: 1596,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_3.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'Llgw2uehGoOa3I3_',
          name: '图片元素',
          desc: '描述信息',
          x: 14.841155234657045,
          y: 96.07220216606498,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 1596,
          naturalWidth: 1099,
          _ratio: 0.6885964912280702,
        },
        {
          type: 'image',
          width: 1165,
          height: 1560,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_2.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'nEx9Dh9PJlPIs32t',
          name: '图片元素',
          desc: '描述信息',
          x: -120,
          y: 128,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 1560,
          naturalWidth: 1165,
        },
        {
          type: 'image',
          width: 1242,
          height: 2208,
          flipx: false,
          flipy: false,
          cropSize: null,
          url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_1.png',
          cornerRadius: [0, 0, 0, 0],
          id: 'VB19wX5QXHz1yfGl',
          name: '图片元素',
          desc: '描述信息',
          x: 0,
          y: 0,
          blur: 0,
          border: { stroke: 'rgba(0,0,0,1)', strokeWidth: 2, visible: false },
          blendMode: 'normal',
          opacity: 1,
          rotation: 0,
          shadow: { x: 0, y: 0, blur: 0, color: 'rgba(0,0,0,0.0)' },
          _dirty: '1',
          _lock: false,
          _hide: false,
          naturalHeight: 2208,
          naturalWidth: 1242,
        },
      ],
    },
  ],
};
